### ISSUE TITLE
Removing bastion host instance in nubis-vpc

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-vpc#12]
Related to https://github.com/Nubisproject/nubis-vpc/issues/9 if we are building jumphosts out of base we no longer need the portion of code that creates the EC2 bastion host instance. Eg: https://github.com/Nubisproject/nubis-vpc/blob/master/Q2.template#L414

**Comment by tinnightcap** [comment]
This work is completed, closing this out now.
