### ISSUE TITLE
Shared security group rules are egress instead of ingress rules

### ISSUE THREAD

**Issue by gene1wood** [Nubisproject/nubis-vpc#20]
Mix of inbound and outbound security groups are defined

The `SssgAllowAnyTcpOut` and `SssgAllowAnyUdpOut` and `SssgAllowAnyIcmpOut` security groups may not be setup correctly as they have `SourceSecurityGroupId` instead of `DestinationSecurityGroupId` so [they may not work](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html). 

If they do work these security groups which allow all ports outbound to the shared service security group should not exist as there should be only two egress security groups, one which allows outbound on all ports to all IPs (aka [Internet access](https://github.com/Nubisproject/nubis-vpc/blob/de14f9a314866865ef19773beed93b1211b1a1d6/Q2.template#L386-L401)) and one which allows outbound on all ports to private IPs. The presence of additional egress security groups will be confusing and encourage incorrectly configured inbound security groups. This control should be made on the inbound side (the `SharedServiceSecurityGroup`) not on the outbound side as it doesn't accomplish the intended goal this way.

The code in question : https://github.com/Nubisproject/nubis-vpc/blob/de14f9a314866865ef19773beed93b1211b1a1d6/Q2.template#L365-L385

**Comment by tinnightcap** [comment]
Egress rules removed in:

https://github.com/Nubisproject/nubis-stacks/pull/156

All existing VPCs redeployed.
