### ISSUE TITLE
[VPC] Break out VPN logic

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-vpc#22]
As we move to account per application the datacenter VPN connection logic should be moved into its own template. This will allow each application to choose weather it needs a VPN connection or not.

Additionally this greatly simplifies deployments for applications that do not require VPN connectivity.

**Comment by gozer** [comment]
A very good idea!

**Comment by gozer** [comment]
This has been closed by Nubisproject/nubis-stacks#99
