### ISSUE TITLE
[VPC] Simplify mappings

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-vpc#23]
In order to make the template simpler for multiple account deployments the lookup maps need to be reduced to a minimum.

 - [ ] Auto-generate values for RegionEnvironment
 - [ ] Parameterize RegionVpcCidr values
 - [ ] Auto-generate availability zones for Region2AZ
 - [ ] Auto-generate lookup domains for DhcpOptions2Vpc

**Comment by gozer** [comment]
Makes sense to me.

**Comment by gozer** [comment]
This has been closed by Nubisproject/nubis-stacks#99
