### ISSUE TITLE
[VPC] Break out Public Subnet

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-vpc#24]
Break out all Public Subnet logic into its own nested stack. This is roughly:

 - PublicRouteTable
 - DefaultRoute
 - PublicSubnetAZ1
 - PublicSubnetAZ2
 - PublicSubnetAZ3
 - PublicSubnetAZ1RouteTableAssociation
 - PublicSubnetAZ2RouteTableAssociation
 - PublicSubnetAZ3RouteTableAssociation

**Comment by gozer** [comment]
Makes sense to me.

**Comment by gozer** [comment]
This has been closed by Nubisproject/nubis-stacks#99
