### ISSUE TITLE
#banhammerintegration - Applications moving to AWS will lose automated BGP blackhole protection

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-vpc#28]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#banhammerintegration

Applications moving to AWS will lose automated BGP blackhole protection

In the datacenters the banhammer automated IP blackholing mechanism protects datacenter resources from attack through automated blocking of threat actor IPs. This functionality is not yet built into nubis. Identified threat actors will not be conveyed to nubis for blocking.

Recommendations :

Build the equivalent mechanism within AWS

**Comment by tinnightcap** [comment]
Once again a duplicate of this issue has been file over [here](https://github.com/nubisproject/nubis-vpc/issues/46). I will close this issue in favor of that as the other issue has some discussion.
