### ISSUE TITLE
#awsnsm - No NSM monitoring in AWS

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-vpc#29]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#awsnsm

No NSM monitoring in AWS

Unlike in the datacenters we currently have not network security monitoring capability (NSM) in AWS.

     https://wiki.mozilla.org/Security/Fundamentals#nsm

Recommendations :

 - Enable NSM monitoring within AWS by deploying Bro on nubis account NAT instances

**Comment by mpurzynski** [comment]
The current master branch of Bro just had a patch landed, that makes deployment of Bro in AWS much easier (no pf_ring necessary, so no custom kernel modules).

To have a NAT instance with Bro running we would need:
1. A NAT instance
2. with 1-2 RPMs installed (that I can produce and make available for download). These RPMs would contain the NSM software and can be 'plug'n'play'
3. A set of configuration files generated and copied to the instance (4 files, two of them dynamically generated depending on some puppet variables)
4. A place to send logs to

I would also like to do one more test before, that should take me not more than a full day.

**Comment by tinnightcap** [comment]
Michal will deliver RPM packages for us to install on the nat instances. @limed will install and configure the nubis puppet foo to install the package on the nat AMIs.

**Comment by tinnightcap** [comment]
This was completed and is now part of the nubis-nat repository.
