### ISSUE TITLE
#banhammerintegration - Support banhammer in Nubis

### ISSUE THREAD

**Issue by gdestuynder** [nubisproject/nubis-vpc#46]
# Original description:
Applications moving to AWS will lose automated BGP blackhole protection

In the datacenters the banhammer automated IP blackholing mechanism protects datacenter resources from attack through automated blocking of threat actor IPs. This functionality is not yet built into nubis. Identified threat actors will not be conveyed to nubis for blocking.

# Proposed mitigation by Nubis team:
We will mitigate this through a manual process by which opsec can ask an IP be blocked.  This is the same scenario that cloud services is in today, they can manually block attackers with security groups but there is no automated integration with the on prem "banhammer" utility.  The ownership of a future automated tool is a bit vague here as banhammer 
was a netops-written tool for on-prem routers.
A manual process has been defined by netops, opsec, and AWS architect. The MOC has agreed to support execution. Process owner Corey S

# Process doc
https://docs.google.com/document/d/1n5APCoJtes6Qr39KhPsHpXU7zrg3n-h9FxghueYqFe8/edit

**Comment by gdestuynder** [comment]
Cloud services already automatically block attackers from mozdef blacklist (FxA) and have their own risk acceptance/remediation plans. Let's not mix their risk management's with Nubis.

A process is a good step forward. I'm not sure the process doc linked is the actual process though, it seems more like a brainstorm doc. Is there an official process doc?

**Comment by gdestuynder** [comment]
The process doc is now at https://mana.mozilla.org/wiki/display/EA/Banning+IP+Addresses+for+a+Nubis+Plan+B+VPC

**Comment by gdestuynder** [comment]
Review of https://mana.mozilla.org/wiki/display/EA/Banning+IP+Addresses+for+a+Nubis+Plan+B+VPC
@
>    A list of AWS accounts and VPC's to with the ban will be applied.
Where can the list be found for Nubis?

>    Credentials to log in to the accounts with sufficient permissions to update the NACL's.

Where can the credentials be found? (or whom to ask - or both)

>    The procedure requires that that the IP addresses that are to be banned be identified. 

Identification of the addresses is out of scope for this procedure.
Who's identifying these addresses usually, and how are they communicated? (for ex who could be "Infosec or MOC" and how could be "Fill bug to component X")

>    A NACL set for each VPC with the name "banhammer".

Since the first time we'll need to use this process it will be in an emergency, i would suggest pre-creating the NACL, or including instructions


Finally: which team is responsible for adding the NACL?

**Comment by RichardWeiss** [comment]
The procedure has been updated to with the requested information.

**Comment by gdestuynder** [comment]
r+

**Comment by tinnightcap** [comment]
Construct a lambda function to query the blocklist or be triggered by the opsec tool that will manage the NACL.

**Comment by tinnightcap** [comment]
This was completed in the nubis-nat repository.
