### ISSUE TITLE
Create DNS entries for BastionHosts (and NAT instances ?)

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-vpc#5]
It would be quite handy for the BastionHosts to have easy to remember DNS entries, instead of their raw amazon DNS names.

Once nubis-vpc is nubis-i-fied, there is a Route53 nested stack just for that.

**Comment by gozer** [comment]
:clock1: 8h

**Comment by gozer** [comment]
Basic Overview:
 - [ ] Create bastion host nubis image
 - [ ] Add EIP to the CF template
 - [ ] Add a Route53 Zone to the CF template
 - [ ] Assign that EIP to a Route53 record
 - [ ] Publish EIP id to Consul
 - [ ] Add node script to retrieve and associate that EIP to the current instance

**Comment by limed** [comment]
- [x] Create bastion host nubis image #6
- [x] Add EIP to the CF template
- [x] Add a Route53 Zone to the CF template
- [x] Assign that EIP to a Route53 record
- [x] Publish EIP id to Consul
Add node script to retrieve and associate that EIP to the current instance

**Comment by davecurado** [comment]
We should probably tear down the VPCs and rebuild them again to get Ed's changes "live"...
of course that means re-doing all the VPN connections again.... ugh.

**Comment by limed** [comment]
So I think we still need to get the instance on the PublicSubnetAZ{1,2,3} VPC this will require some work on the ec2 template

**Comment by limed** [comment]
Possibly related to nubisproject/nubis-stacks#53

**Comment by tinnightcap** [comment]
I believe this work is complete. If anything is outstanding, please let me know.
